//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ДЗ__55_до_22._01._23_WPF_Расширения_разметки {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemsMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemsMenu() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ДЗ__55_до_22._01._23_WPF_Расширения_разметки.ItemsMenu", typeof(ItemsMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты. Адрес: 125009 Москва, Брюсов пер. 7, подъезд 1, оф. 1 (метро Охотный ряд). Тел. +7 (495) 668-31-61/ -62/ -63,   +7 495 692-38-95 +7 495 692-20-59 +7 495 692-11-30.
        /// </summary>
        internal static string ContactsText {
            get {
                return ResourceManager.GetString("ContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Французский.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индонезийский.
        /// </summary>
        internal static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как путешествовать по России на велосипеде: идеи и советы. Новичкам стоит попробовать свои силы в однодневных путешествиях — несложных и недлинных. Маршруты для первых велопоходов выбирайте тщательно, учитывайте не только дистанцию, но и профиль дороги: не должно быть ни затяжных подъёмов, ни высоких холмов. Чем ровнее она будет — тем лучше. Не стоит приближаться к загруженным большим трассам с сильным движением, даже если по ним разрешено ездить на велосипеде. Находите объездные пути по просёлочным дорогам [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MainText {
            get {
                return ResourceManager.GetString("MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширения разметки.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 17 ноября, 2023 &quot;Чемпионат России по велогонкам.
        /// </summary>
        internal static string NewsItem1 {
            get {
                return ResourceManager.GetString("NewsItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 24 декабря, 2023 &quot;История велотуризма в России. Открытая лекция.
        /// </summary>
        internal static string NewsItem2 {
            get {
                return ResourceManager.GetString("NewsItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуги.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наша помощь в организации Вашего путешествия не ограничивается бронированием 
        /// гостиниц и экскурсий. Вы можете положиться на нас в решении любых вопросов, связанных с подготовкой к нему. Мы поможем Вам:составить оптимальный маршрут Вашего путешествия с посещением интересных для Вас достопримечательностей и  забронировать отели по пути следования;забронировать авиабилет на удобный для Вас рейс российской или международной авиакомпании или железнодорожный билет,
        ///  заказать трансфер по городу или между городам [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ServicesText {
            get {
                return ResourceManager.GetString("ServicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испанский.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
    }
}
